import {readFileSync,writeFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {QaReportSchema,QaIssueSchema} from '../../../../src/schemas/index.ts';
import {NaturalFlowEvidenceSchema} from '../../../../src/schemas/natural-flow.ts';
import {PerceptualQaReportSchema} from '../../../../src/schemas/product-experience.ts';
import {TaskSchema,MatrixSchema,ResultSchema} from '../../qa-recovery-20260907/recovery-schemas.ts';
const run=resolve('runs/mobile-slice-adaptation-20260830'),attempt=`${run}/recovery-human-20260907/attempt-1`,out=`${attempt}/qa`;
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const task=TaskSchema.parse(read(`${attempt}/qa-task.json`));
const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const buildHash='c8f24a360b3dc8963beccc87bc1db10e62f2dda4276afdf0ffb6074240d4636c';
if(hash(`${task.workspace}/dist/index.html`)!==buildHash)throw new Error('Build changed');
const save=(name:string,data:unknown)=>{const p=`${out}/${name}`;writeFileSync(p,JSON.stringify(data,null,2)+'\n');return p;};
const png=(device:string,name:string)=>`${out}/${device}/frames/${name}`;
const trace=(device:string)=>`${out}/${device}/recording.json`;
const names=['portrait-1','portrait-2','portrait-3','desktop-1','desktop-2','desktop-3'];
const captures=names.map(n=>({name:n,...read(trace(n))}));
const matrix=MatrixSchema.parse(read(`${run}/qa-recovery-20260907/reproduction-matrix.json`));
const now=new Date().toISOString();
for(const c of matrix.cells){const mobile=c.viewport==='390x844',name=mobile?'portrait-1':'desktop-1',kind=c.id.split('-')[1];c.status='BLOCKED';c.evidence=[trace(name)];
 if(kind==='INPUT'){c.status='PASS';c.notes='默认首个完整rune-1现在明确可见，球底与opening-table-a顶面贴合；普通输入后刀接近同一球体，出现切面、分开的两半和局部+1。不是用切开后的半球代替完整态验收。';c.evidence.push(png(name,'startup.png'),png(name,mobile?'dense-0019.jpg':'dense-0008.jpg'),png(name,mobile?'dense-0024.jpg':'dense-0020.jpg'));}
 if(kind==='GROUND'){c.notes='opening-table-a独立厚柱底部接地在两视口均可见。opening-table-b区域与main runway重叠，截图中连续落地外观可见，但b自身底部没有独立暴露；其精确接地像素归属仍BLOCKED，不能只用a或runway的通过关闭b。';c.evidence.push(png(name,'startup.png'),png(mobile?'portrait-3':'desktop-3','frame-0000.png'));if(!mobile){c.status='FAIL';c.notes+=' 完整桌面旅程中level1-reward-shelf仍是悬空薄板，late-table柱底仍未接到白色地面，因此整个GROUND合同未通过。';c.evidence.push(png('desktop-3','frame-0008.png'),png('desktop-3','frame-0011.png'));}}
 if(kind==='STACK'){c.status='FAIL';c.notes='接近阶段可见绿色双排砖块与白台之间存在明显空隙，没有可辨承托；本轮未取得同一水平重叠堆叠接触→分开→失去承托→落地的完整证据。图像确认的承托关系失败与缺少动态链证据分别保留。';c.evidence.push(png(mobile?'portrait-1':'desktop-3',mobile?'frame-0010.png':'frame-0008.png'));}
 if(kind==='REWARD'){c.notes='首切密集帧显示完整态→切面与局部+1→明显分离，奖励附着位置可见；首张切开帧的累计值已变化。首切附近仍有约200ms采集/停帧间隔，因此不能断言已经满足完成→分离→局部奖励→累计同步的严格先后。';c.evidence.push(png(name,mobile?'dense-0019.jpg':'dense-0008.jpg'),png(name,mobile?'dense-0020.jpg':'dense-0009.jpg'),png(name,mobile?'dense-0024.jpg':'dense-0020.jpg'));}
 if(kind==='PRESSURE'){c.notes='可见失败面板与重玩路径已验证。固定节奏下本轮主要是跌出路线失败，未取得同一尖刺ID预警→接触→可归因失败全链；不以内部failReason替代危险分支像素。';c.evidence.push(png(mobile?'portrait-2':'desktop-2','terminal.png'),png(mobile?'portrait-2':'desktop-2','replay.png'));if(!mobile)c.evidence.push(png('desktop-3','frame-0005.png'));}
 if(kind==='FINISH'){c.notes=mobile?'三种已声明手机固定节奏都自然失败，未到完整赢结算；这是有限策略的覆盖缺口，不证明游戏不能完成。第一轮还受已修正的跌出路线文案漏判影响。':'桌面950ms绝对节奏自然完成×4、分数60，完整完成面板后点击重玩并回到首关。终点墙上方结果带依旧裁切、倍率未贴近对应区域，右上微小图例不能替代；完整自然闭环通过不关闭终点感知失败。';if(!mobile){c.status='FAIL';c.evidence.push(png('desktop-3','frame-0011.png'),png('desktop-3','terminal.png'),png('desktop-3','replay.png'));}else c.evidence.push(png('portrait-3','terminal.png'),png('portrait-3','replay.png'));}
}
const matrixPath=save('reproduction-matrix.json',MatrixSchema.parse(matrix));
const assigned=MatrixSchema.parse({schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,cells:['390x844','1100x720'].flatMap(viewport=>{const name=viewport==='390x844'?'portrait-1':'desktop-1',later=viewport==='390x844'?'portrait-3':'desktop-3';return[
 {id:`L1-FIRST-TARGET-VISIBILITY-${viewport}`,objectType:'rune-1 sigil sphere',stateBranch:'intact before first cut → contact → split',renderer:'default main Three.js intact scalar-material path',viewport,acceptance:'完整物体可见且底部与承托接触；自然首次输入切到同一对象。',status:'PASS',evidence:[png(name,'startup.png'),png(name,viewport==='390x844'?'dense-0024.jpg':'dense-0020.jpg'),trace(name)],notes:'完整球体、接触及分离已逐张检查。'},
 {id:`L1-OPENING-TABLE-A-${viewport}`,objectType:'opening-table-a',stateBranch:'startup/intact → first cut',renderer:'default ThreeWorldRenderer.syncSupports',viewport,acceptance:'具备从薄顶面延伸至实际地面的厚基座，并承托首个物体。',status:'PASS',evidence:[png(name,'startup.png'),trace(name)],notes:'首个独立柱体和底部接地可见；支持的是exact opening-table-a。'},
 {id:`L1-OPENING-TABLE-B-${viewport}`,objectType:'opening-table-b',stateBranch:'startup/intact → approach',renderer:'default ThreeWorldRenderer.syncSupports',viewport,acceptance:'同一opening-table-b基座接地与承托关系有自然可见证据。',status:'BLOCKED',evidence:[png(later,'frame-0000.png'),trace(later),`${task.workspace}/src/three-world-renderer.ts`],notes:'源码精确分支已补入、结束于实际地面；但b位于main runway内部，默认画面基座重叠。当前截图只确认该区域连续接地，不能独立归属b的底部；这属于证据缺口，不宣称代码修复失败，也不推定必须改变布局。'}];})});
const assignedPath=save('assigned-opening-review.json',assigned);
const naturalPaths:string[]=[];
for(const cap of captures){const observedActualFailure=cap.observations.some((o:any)=>o.state?.status==='failed'&&o.terminalCopy?.startsWith('跌出路线')),first=cap.name.endsWith('-1');
 const blockers=first?['QA首轮漏匹配真实跌出路线面板；原始截图已证明发生失败，但记录器未点重玩。问题已在第2、3轮修正；不计作游戏无法终结。']:[];
 if(!cap.unchanged)blockers.push('构建在QA期间变化');
 const evidence=NaturalFlowEvidenceSchema.parse({schemaVersion:1,startedFromReset:true,actions:[`fresh default index.html; fixed absolute cadence ${read(`${cap.outputDirectory}/policy.json`).cadenceMs}ms；实际时间见recording.json`,'观察、screencast帧、完整视频和输入独立；未使用内部状态决定点击'],transitions:[{name:'startup-to-core',changed:cap.observations.some((o:any)=>o.state?.cuts>0),evidence:trace(cap.name)},{name:'true-terminal',changed:!!cap.terminal||observedActualFailure,evidence:cap.terminal?png(cap.name,'terminal.png'):png(cap.name,'end.png')},{name:'visible-replay',changed:cap.replay?.state?.status==='ready',evidence:cap.replay?png(cap.name,'replay.png'):trace(cap.name)}],completion:cap.terminal?.outcome==='won'?'settlement':cap.terminal||observedActualFailure?'terminal':'none',replayObserved:cap.replay?.state?.status==='ready',forbiddenOperations:[],screenshots:cap.frames.map((f:any)=>f.path),passed:blockers.length===0&&!!cap.terminal&&!!cap.replay,blockers,runner:'independent-QAAgent-absolute-cadence',buildHash,runtime:'Chromium default index.html, no rebuild',device:{...cap.viewport,label:cap.name},observedAt:cap.observedAt});
 naturalPaths.push(save(`${cap.name}-natural-flow.json`,evidence));
}
const failLog=`${attempt}/green-suite.log`;
const unitNames=[...new Set(readFileSync(failLog,'utf8').split('\n').filter(l=>l.startsWith('✖ ')&&!l.includes('failing tests:')).map(l=>l.replace(/^✖ /u,'').replace(/ \([^)]*ms\)$/u,'')))];
if(unitNames.length!==6)throw new Error(`Expected six retained failing checks, got ${unitNames.length}`);
const qaIssues=unitNames.map((name,i)=>QaIssueSchema.parse({id:`RETAINED-UNIT-${i+1}`,severity:'error',message:name,evidence:failLog}));
qaIssues.push(QaIssueSchema.parse({id:'REMAINING-PERCEPTUAL-CONTRACT',severity:'error',message:'后段承托/堆叠仍存在已观察缺口，终点标签/裁切感知失败；本轮未修这些分支。',evidence:matrixPath}));
const qaPath=save('qa-report.json',QaReportSchema.parse({schemaVersion:1,passed:false,checks:[...unitNames.map(name=>({name,passed:false,evidence:failLog})),{name:'completed build unchanged in every QA capture',passed:captures.every(c=>c.unchanged),evidence:`${out}/build-binding.json`},{name:'desktop natural full settlement/replay',passed:captures.find(c=>c.name==='desktop-3').terminal?.outcome==='won',evidence:trace('desktop-3')},{name:'assigned opening exact-branch review complete',passed:assigned.cells.every(c=>c.status==='PASS'),evidence:assignedPath}],issues:qaIssues,screenshots:[png('portrait-1','startup.png'),png('desktop-1','startup.png'),png('desktop-3','terminal.png')],consoleLog:trace('desktop-3'),testedAt:now}));
const perceptualPath=save('perceptual-qa-report.json',PerceptualQaReportSchema.parse({schemaVersion:1,artifactType:'perceptual-qa-report',game:task.targetGame,passed:false,checkedAt:now,features:matrix.cells.map(c=>({featureId:c.id,playerVisible:c.status==='PASS',naturalTriggerVerified:c.status==='PASS',screenshotEvidence:c.evidence.filter(p=>/\.(png|jpg)$/u.test(p)),evidence:c.evidence,notes:[`${c.status}: ${c.notes}`]}))}));
const blockers=['工程全量测试仍有6项失败，已逐项保留原始日志。','首个完整目标与opening-table-a在双视口通过；opening-table-b自身底部被runway重叠，独立像素归属缺证。','后段台面及绿色堆叠承托关系未通过；精确散落/落地链未验证。','奖励严格先后与尖刺预警/归因分支仍缺证。','桌面自然完成×4并重玩，但终点结果带标签与裁切仍失败；手机三种固定节奏只观察到失败重玩，赢结算缺证。'];
const naturalPath=save('qa-natural-journey-report.json',NaturalFlowEvidenceSchema.parse({schemaVersion:1,startedFromReset:true,actions:['双视口各3种预先声明策略：800ms、650ms、950ms，绝对时钟普通输入','desktop-3自然完成×4分数60；其余运行发生跌出路线；第2、3轮真实面板后重玩','首轮文案漏判仅作为已修正QA问题，不推定为产品终态缺陷'],transitions:matrix.cells.map(c=>({name:c.id,changed:c.status==='PASS',evidence:matrixPath})),completion:'settlement',replayObserved:true,forbiddenOperations:[],screenshots:matrix.cells.flatMap(c=>c.evidence.filter(p=>/\.(png|jpg)$/u.test(p))),passed:false,blockers,runner:'independent-QAAgent-whole-slice-gate',buildHash,runtime:'desktop and mobile independently reviewed',observedAt:now}));
save('build-binding.json',{schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,expectedBuildSha256:buildHash,actualFinalSha256:hash(`${task.workspace}/dist/index.html`),captures:captures.map(c=>({directory:c.outputDirectory,unchanged:c.unchanged,sourceBefore:`${c.outputDirectory}/source-before.json`,sourceAfter:`${c.outputDirectory}/source-after.json`})),fixResult:`${attempt}/fix-result.json`,fixResultSha256:hash(`${attempt}/fix-result.json`),retainedUnitLog:failLog,retainedUnitLogSha256:hash(failLog),referenceManifest:`${run}/qa-recovery-20260907/reference-frames/manifest.json`,referenceManifestSha256:hash(`${run}/qa-recovery-20260907/reference-frames/manifest.json`)});
save('methodology.json',{targetGame:task.targetGame,workspace:task.workspace,sourceModified:false,rebuilds:0,browserContexts:6,cleanup:'all recorder processes returned after closing browser and preview',assignedOpeningStatus:'PARTIAL: rune-1 and opening-table-a PASS both viewports; b occlusion evidence BLOCKED',wholeSliceStatus:'BLOCKED',runnerIssue:`${run}/recovery-human-20260907/qa-tools/runner-resolution.json`,actualInputTiming:captures.map(c=>({name:c.name,maxDispatchLatenessMs:Math.max(...c.inputs.filter((i:any)=>i.kind!=='skipped-late-deadline').map((i:any)=>i.dispatchedMs-i.plannedMs)),denseMaxGapMs:c.denseMaxGapMs,skippedInputs:c.inputs.filter((i:any)=>i.kind==='skipped-late-deadline').length})),interpretation:'本轮仅取证，无新增因果已证实回归；浮空与标签问题是既有未分配分支。每张使用的证据均实际view_image检查。手机策略覆盖不足不等同于产品不可通关。'});
const result=ResultSchema.parse({schemaVersion:1,role:'QAAgent',targetGame:task.targetGame,workspace:task.workspace,status:'BLOCKED',reportPaths:[qaPath,naturalPath,perceptualPath,matrixPath,assignedPath,...naturalPaths,`${out}/build-binding.json`,`${out}/methodology.json`,`${out}/evidence-sha256.json`],blockers,sourceModified:false,summary:'首个完整rune-1与opening-table-a双视口自然像素验收通过；b基座被runway重叠，独立像素归属仍缺证。桌面950ms自然完成×4分数60并重玩；手机真实失败后可重玩。保留6项单测失败和未通过的全首关感知项；未改游戏或重建。'});
save('result.json',result);
function files(p:string):string[]{return readdirSync(p).sort().flatMap(n=>statSync(`${p}/${n}`).isDirectory()?files(`${p}/${n}`):[`${p}/${n}`]);}
save('evidence-sha256.json',{schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,expectedBuildSha256:buildHash,files:files(out).filter(p=>p!==`${out}/evidence-sha256.json`).map(path=>({path,sha256:hash(path)}))});
console.log(JSON.stringify(result));
