import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {TriageSchema,AuthorizationSchema,RepairIssueSchema,AttemptTaskSchema,CycleStateSchema} from './schemas.ts';
const run='/Users/kker/Documents/ChatGPT/妖怪夜市/runs/mobile-slice-adaptation-20260830';
const base=`${run}/recovery-human-20260907-followup`,workspace=`${run}/workspace/prototype-a`,old=`${run}/recovery-human-20260907`,cycleId='human-review-20260907-l1-followup',thread='01a07540-7ee1-7c01-899b-0ea12bde1f19';
const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const oldState=`${old}/cycle-state.json`,build=`${workspace}/dist/index.html`,oldMatrix=`${old}/attempt-5/qa/reproduction-matrix.json`,oldReport=`${old}/cycle-final-report.md`,stackRec=`${old}/attempt-4/qa/desktop-1/recording.json`,phoneRec=`${old}/attempt-5/qa/portrait-1/recording.json`,contract=`${old}/../qa-recovery-20260907/active-slice-contract.json`;
mkdirSync(base,{recursive:true});
const ev=(path:string,provenance:'verified-run-artifact'|'verified-build'|'verified-reference')=>({path,sha256:hash(path),provenance});
const triage=TriageSchema.parse({schemaVersion:1,artifactType:'repair-triage',cycleId,targetGame:'mobile-slice-adaptation-20260830',workspace,trigger:'用户明确要求按照流程开启新的修复周期；上一周期达到5次上限且保留了两个未关闭的体验门。',previousCycle:{path:oldState,status:'BLOCKED_MAX_ATTEMPTS',sha256:hash(oldState)},currentBuild:{path:build,sha256:hash(build)},issues:[
 {id:'L1-STACK-NATURAL-CHAIN',severity:'error',classification:'unresolved-product-or-evidence',objectType:'same visible stack-a/b and support',stateBranch:'intact support → blade contact → cut/separate → unsupported upper falls/rests',renderer:'game-core → ThreePresentationModel → ThreeWorldRenderer/CutVisualEntity',scope:'Level1 only; both 390x844 and 1100x720; no other levels or factory code',reproduction:{steps:['从新的浏览器上下文进入首关','用正常点击/触摸沿可见轨迹接近 stack-a 或 stack-b','记录同一对象的完整态、接触、切面、上层失去承托、下落和落地画面'],observed:['工程测试已证明对象可碰撞、存在真实 supportedBy 关系并释放上层对象','上一周期多次自然录制没有同时捕获完整可见链，无法区分纯取证缺口和呈现/交互缺陷'],status:'UNRESOLVED'},acceptance:['两个视口各有自然输入录制，连续显示同一 ID 对象由承托到切开、上层掉落并落地','录制中不使用 debug、状态注入或内部状态决定点击','若实现已正确，仅补证据并保持源码不变；若画面显示同一对象未掉落/落地，只修改因果实现'],evidence:[ev(oldMatrix,'verified-run-artifact'),ev(stackRec,'verified-run-artifact'),ev(`${old}/attempt-5/fix-result.json`,'verified-run-artifact')]},
 {id:'L1-FINISH-PHONE-ROUTE',severity:'error',classification:'unresolved-product-or-evidence',objectType:'finish outcome lanes, settlement and replay',stateBranch:'portrait 390x844 approach → choice/contact → world result → settlement → replay',renderer:'createCameraSpec → ThreeWorldRenderer → finish-label-layout → DOM HUD',scope:'Level1 phone route only, with desktop comparison; no new finish mechanics',reproduction:{steps:['从新的 390x844 浏览器上下文进入首关','只用正常触摸和可见反馈调整节奏，进入终点结果区','观察选择、世界结果、结算面板和重玩入口'],observed:['上一周期第4次桌面录制曾自然通关并重玩','最后一次手机录制在前段跌出路线，无法证明手机终点不可达，也没有完成最终手机门禁'],status:'UNRESOLVED'},acceptance:['390x844 fresh natural-input trace reaches a visible finish choice, settlement and replay','结果栏在选择前可辨，接触结果先于结算，重玩后回到首关 ready','若只是输入覆盖不足，保留构建并补取证；不得因脚本失败擅自改动核心节奏'],evidence:[ev(phoneRec,'verified-run-artifact'),ev(`${old}/attempt-4/qa/desktop-1/frames/terminal.png`,'verified-run-artifact'),ev(oldReport,'verified-run-artifact')]}
],sourcePrecedence:['当前用户授权与纠正','已验证且绑定本 run 的自然录制与 QA 回执','当前 active-slice-contract 及其哈希','历史 Agent 假设；未验证媒体不使用'],createdAt:new Date().toISOString()});
const triagePath=`${base}/triage.json`;writeFileSync(triagePath,JSON.stringify(triage,null,2)+'\n',{flag:'wx'});
const auth=AuthorizationSchema.parse({schemaVersion:1,artifactType:'human-repair-authorization',cycleId,targetGame:'mobile-slice-adaptation-20260830',workspace,userReply:'按照流程开启新的修复吧',authorizedAt:new Date().toISOString(),maximumAttempts:5,triagePath,triageSha256:hash(triagePath),previousCyclePath:oldState,previousCycleSha256:hash(oldState),storedThreadId:thread,historyPreserved:true});const authPath=`${base}/authorization.json`;writeFileSync(authPath,JSON.stringify(auth,null,2)+'\n',{flag:'wx'});
const issuePackets=triage.issues.map(i=>RepairIssueSchema.parse({id:i.id,severity:i.severity,message:`${i.objectType}：${i.reproduction.observed.join('；')}`,evidence:i.evidence[0].path,classification:i.classification,acceptance:i.acceptance}));
const task=AttemptTaskSchema.parse({schemaVersion:1,artifactType:'repair-task',route:'formal-fixer',cycleId,attempt:1,targetGame:'mobile-slice-adaptation-20260830',workspace,authorizationPath:authPath,outputDirectory:`${base}/attempt-1`,issues:issuePackets,triagePath,contractPath:contract,contractSha256:hash(contract),expectedBuildSha256:hash(build),instructions:['这是新授权周期第1/5次，继续使用原 stored Fixer 任务；旧周期 attempt-1 至 attempt-5 只读保留。','先读取 triage.json、active-slice-contract 和 failure-pressure-contract；不要把上一周期的“证据缺口”直接当成实现缺陷。','先写 preflight.json，再为每个真实缺陷写 RED 测试；若仅是取证缺口，明确记录并不要发明玩法或改动源码。','只修改 Level1 因果相关文件；不可改共享工厂、其他游戏、发布配置或未涉及关卡。','必须执行 test-first、完整 tests、lint、typecheck；最多一次 pnpm build。','完成后输出严格 FixResultSchema 的 fix-result.json，状态只写 READY_FOR_INDEPENDENT_QA 或 BLOCKED；独立 QA 使用正常输入和玩家可见证据，不接受状态注入作为通过。'],outputSchema:`${base}/schemas.ts#FixResultSchema`});mkdirSync(`${base}/attempt-1`,{recursive:true});const taskPath=`${base}/attempt-1/task.json`;writeFileSync(taskPath,JSON.stringify(task,null,2)+'\n',{flag:'wx'});
const state=CycleStateSchema.parse({schemaVersion:1,cycleId,targetGame:'mobile-slice-adaptation-20260830',workspace,maximumAttempts:5,attemptsStarted:1,attemptsCompleted:0,currentAttempt:1,status:'FIXING',authorizationPath:authPath,storedThreadId:thread,historyPreserved:true,attempts:[{attempt:1,taskPath,status:'RESERVED',reservedAt:new Date().toISOString()}]});writeFileSync(`${base}/cycle-state.json`,JSON.stringify(state,null,2)+'\n',{flag:'wx'});
writeFileSync(`${base}/README.md`,['# 小李飞刀：新修复周期','',`周期 ${cycleId}，目标 mobile-slice-adaptation-20260830，唯一工作区 ${workspace}。`,'','上一周期 human-review-20260907 已达到5次上限并封存。本周期由用户“按照流程开启新的修复吧”明确授权，最多5次，旧记录不覆盖。先处理两个未决 triage：同一堆叠自然生命周期，以及手机终点自然覆盖。','','- triage：triage.json','- 授权：authorization.json','- 当前状态：cycle-state.json','- 第1次任务：attempt-1/task.json','- 上一周期：../recovery-human-20260907/cycle-final-report.md',''].join('\n'),{flag:'wx'});
console.log(JSON.stringify({validated:true,cycleId,triagePath,taskPath,buildSha256:hash(build)}));
