import { z } from 'zod';
const T = z.string().trim().min(1);
const H = z.string().regex(/^[a-f0-9]{64}$/u);
const Evidence = z.object({path:T,sha256:H,provenance:z.enum(['verified-run-artifact','verified-build','verified-reference'])}).strict();
export const TriageIssueSchema = z.object({
  id:T, severity:z.enum(['error','warning']), classification:z.enum(['confirmed-product-defect','unresolved-product-or-evidence','evidence-gap']),
  objectType:T, stateBranch:T, renderer:T, scope:T, reproduction:z.object({steps:z.array(T).min(1),observed:z.array(T).min(1),status:z.enum(['REPRODUCED','NOT_REPRODUCED','UNRESOLVED'])}).strict(),
  acceptance:z.array(T).min(1), evidence:z.array(Evidence).min(1)
}).strict();
export const TriageSchema = z.object({schemaVersion:z.literal(1),artifactType:z.literal('repair-triage'),cycleId:T,targetGame:T,workspace:T,trigger:T,previousCycle:z.object({path:T,status:z.literal('BLOCKED_MAX_ATTEMPTS'),sha256:H}).strict(),currentBuild:z.object({path:T,sha256:H}).strict(),issues:z.array(TriageIssueSchema).min(1),sourcePrecedence:z.array(T).min(1),createdAt:T}).strict();
export const AuthorizationSchema = z.object({schemaVersion:z.literal(1),artifactType:z.literal('human-repair-authorization'),cycleId:T,targetGame:T,workspace:T,userReply:z.literal('按照流程开启新的修复吧'),authorizedAt:T,maximumAttempts:z.literal(5),triagePath:T,triageSha256:H,previousCyclePath:T,previousCycleSha256:H,storedThreadId:T,historyPreserved:z.literal(true)}).strict();
export const RepairIssueSchema = z.object({id:T,severity:z.enum(['error','warning']),message:T,evidence:T,classification:z.enum(['confirmed-product-defect','unresolved-product-or-evidence','evidence-gap']),acceptance:z.array(T).min(1)}).strict();
export const AttemptTaskSchema = z.object({schemaVersion:z.literal(1),artifactType:z.literal('repair-task'),route:z.literal('formal-fixer'),cycleId:T,attempt:z.number().int().min(1).max(5),targetGame:T,workspace:T,authorizationPath:T,outputDirectory:T,issues:z.array(RepairIssueSchema).min(1),triagePath:T,contractPath:T,contractSha256:H,expectedBuildSha256:H,instructions:z.array(T).min(1),outputSchema:T}).strict();
export const FixResultSchema = z.object({schemaVersion:z.literal(1),role:z.literal('FixerAgent'),route:z.literal('formal-fixer'),cycleId:T,attempt:z.number().int().min(1).max(5),targetGame:T,workspace:T,storedThreadId:T,status:z.enum(['READY_FOR_INDEPENDENT_QA','BLOCKED']),why:T,contextIntentionallyOmitted:z.array(T),rootCauses:z.array(z.object({issueId:T,objectType:T,stateBranch:T,renderer:T,evidence:z.array(T).min(1)}).strict()),filesChanged:z.array(T),tests:z.array(z.object({command:T,exitCode:z.number().int(),logPath:T,phase:z.enum(['RED','GREEN','LINT','TYPECHECK'])}).strict()),build:z.object({command:T,exitCode:z.number().int(),logPath:T,count:z.literal(1),path:T,sha256:H}).nullable(),remainingEvidenceGaps:z.array(T),completedAt:T}).strict();
export const CycleStateSchema = z.object({schemaVersion:z.literal(1),cycleId:T,targetGame:T,workspace:T,maximumAttempts:z.literal(5),attemptsStarted:z.number().int().min(0).max(5),attemptsCompleted:z.number().int().min(0).max(5),currentAttempt:z.number().int().min(0).max(5),status:z.enum(['READY_FOR_FIX','FIXING','QA','READY_FOR_NEXT_FIX','COMPLETE','BLOCKED_MAX_ATTEMPTS']),authorizationPath:T,storedThreadId:T,historyPreserved:z.literal(true),attempts:z.array(z.object({attempt:z.number().int().min(1).max(5),taskPath:T,status:z.enum(['RESERVED','FIXING','QA','BLOCKED','PASS']),fixReceiptPath:T.optional(),qaReceiptPath:T.optional(),reservedAt:T}).strict())}).strict();
export const DispatchRejectionSchema = z.object({schemaVersion:z.literal(1),artifactType:z.literal('dispatch-rejection'),cycleId:T,targetGame:T,workspace:T,action:T,status:z.literal('REJECTED_BY_AUTOMATIC_APPROVAL_REVIEW'),reason:T,taskPath:T,triagePath:T,sourceModified:z.literal(false),recordedAt:T}).strict();
