import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {resolve} from 'node:path';import {TaskSchema} from '../qa-recovery-20260907/recovery-schemas.ts';import {FixResultSchema} from './schemas.ts';
const run=resolve('runs/mobile-slice-adaptation-20260830'),base=`${run}/recovery-human-20260907`,n=Number(process.argv[2]),folder=`${base}/attempt-${n}`;const fix=FixResultSchema.parse(JSON.parse(readFileSync(`${folder}/fix-result.json`,'utf8')));if(!fix.build||fix.build.exitCode!==0)throw new Error('build missing');
const prior=TaskSchema.parse(JSON.parse(readFileSync(`${base}/qa-prepare-task.json`,'utf8')));mkdirSync(`${folder}/qa`,{recursive:true});
const task=TaskSchema.parse({...prior,outputDirectory:`${folder}/qa`,sourceTriage:[`${folder}/task.json`,`${run}/qa-recovery-20260907/source-diagnosis.json`],sourceMatrices:[`${run}/qa-recovery-20260907/independent-qa/reproduction-matrix.json`],instructions:[
'Execute independent QA NOW on completed Fixer build. Own only this outputDirectory plus reusable qa-tools; never edit game workspace, source, tests or dist. Keep old audit evidence immutable. Root owns cycle ledger. No rebuild.',
`Exact dist/index.html SHA256 must remain ${fix.build.sha256}. FixResultSchema result at ${folder}/fix-result.json and receipt at ${folder}/fix-receipt.json are validated. Verify before and after.`,
`Use your prepared qa-tools runner with dense first-cut visible evidence and decoupled declared tap timing. Read locked failure pressure ${base}/failure-pressure-contract.json and reviewed acceptance ${run}/qa-recovery-20260907/active-slice-contract.json.`,
`Read source-grounded reward meaning ${base}/reward-acceptance-clarification.json. Do not add an unrequested non-overlap or sub-frame timing rule. Verify fresh intact-state zero gain, first post-cut reward with visible separation/local attachment, and synchronized total; old archive analysis is explanatory only, not current-build PASS. Run gameplay contexts sequentially, not concurrently, so headless rendering load does not confound viewport comparison.`,
`Prioritize the exact issues repaired in attempt${n}: ${fix.rootCauses.map(c=>c.issueId).join(', ')}. Preserve opening regression coverage: intact rune-1 visible before cut, opening-table-a AND opening-table-b bases visibly meet ground with target support. Inspect390x844 and1100x720 fresh default entry. Test later stack/finish branches named in this fix with natural player-visible evidence.`,
'Also run full default natural journey through terminal/settlement/replay on phone and desktop. Bounded up to3 different declared fixed cadence policies per viewport if needed, not hidden-state auto-play. Failures preserve causal visible evidence; an actual terminal panel is required before replay. Collect reward sequence and later pressure/finish snapshots for subsequent repairs. Fixture traces cannot close natural matrix.',
'All12 contract cells remain in final matrix, independently review what you observe. Distinguish assigned issue result from whole slice gate. Missing unassigned evidence remains BLOCKED. Engineering report must derive actual test failures from THIS attempt FixResultSchema logs; do not retain stale prior failures after new tests pass, and do not mask actual failures with screenshots.',
'Use QaReportSchema,NaturalFlowEvidenceSchema,PerceptualQaReportSchema,MatrixSchema,ResultSchema. Add precise new QaIssueSchema issues for actual regressions observed; missing capture is QA work, not an inferred game defect. Every report/evidence has source/build hash and paths. Return ResultSchema-validated result.json after cleanup. Do not request user input or start repairs.'
],acceptance:['Exact opening intact and both opening supports verified with natural visible evidence at both viewports.','Default journey captured through true terminal/replay or real blocker identified.','All12 cells have independent results; no overall pass if engineering tests or perceptual cells remain blocked.']});writeFileSync(`${folder}/qa-task.json`,JSON.stringify(task,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({validated:true,taskPath:`${folder}/qa-task.json`,schemaPath:`${run}/qa-recovery-20260907/recovery-schemas.ts#TaskSchema`,expectedBuildSha256:fix.build.sha256}));
