import {finalChecksPass} from './final-checks.ts';
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{resolve}from'node:path';import{createHash}from'node:crypto';import{AttemptTaskSchema,AuthorizationSchema}from'./schemas.ts';import{QaReportSchema}from'../../../src/schemas/index.ts';
const run=resolve('runs/mobile-slice-adaptation-20260830'),base=`${run}/recovery-human-20260907`,prior=`${run}/qa-recovery-20260907`,read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const n=Number(process.argv[2]),state=read(`${base}/cycle-state.json`),auth=AuthorizationSchema.parse(read(`${base}/authorization.json`));if(n!==state.attemptsStarted+1||n>5||state.status!=='READY_FOR_NEXT_FIX')throw new Error('no authorized next attempt');const prev=`${base}/attempt-${n-1}`,receipt=read(`${prev}/qa-receipt.json`),old=read(`${prior}/fixer-handoff.json`);
if(receipt.status!=='BLOCKED')throw new Error('prior pass');const runtime=QaReportSchema.parse(read(`${prev}/qa/qa-report.json`)),engineering=QaReportSchema.parse(read(`${base}/engineering-qa-report.json`));
const bothPassed=(prefix:string)=>[390,1100].every(w=>receipt.passingCheckIds.includes(`${prefix}-${w}`));
const lastFix=read(`${prev}/fix-result.json`);
const engineeringStillFailed=!finalChecksPass(lastFix.tests);
let issues=[...old.issues.filter((i:any)=>(i.id==='L1-STACK-DECORATIVE-SUBSTITUTION'&&!bothPassed('L1-STACK'))||(i.id==='L1-FINISH-VISIBILITY'&&!bothPassed('L1-FINISH'))),...(engineeringStillFailed?engineering.issues:[]),...runtime.issues.filter(i=>i.severity==='error'&&!i.id.startsWith('RETAINED-UNIT-'))];
for(const id of ['L1-OPENING-TABLE-BRANCH','L1-FIRST-TARGET-VISIBILITY']){const prefix=id==='L1-OPENING-TABLE-BRANCH'?'L1-GROUND':'L1-INPUT';if(![390,1100].every(w=>receipt.passingCheckIds.includes(`${prefix}-${w}`)))issues.push(old.issues.find((i:any)=>i.id===id));}
issues=issues.filter((i,index,a)=>a.findIndex(j=>j.id===i.id)===index);
const outputDirectory=`${base}/attempt-${n}`;mkdirSync(outputDirectory,{recursive:true});
const task=AttemptTaskSchema.parse({schemaVersion:1,role:'FixerAgent',route:'formal-fixer',cycleId:auth.cycleId,attempt:n,targetGame:auth.targetGame,workspace:auth.workspace,authorizationPath:`${base}/authorization.json`,outputDirectory,issues,matrixPath:`${prev}/qa/reproduction-matrix.json`,contractPath:`${prior}/active-slice-contract.json`,expectedBuildSha256:sha(`${auth.workspace}/dist/index.html`),instructions:[
`This is attempt${n}/5 in the already explicitly user-authorized cycle. Resume stored original Fixer thread. Root owns cycle-state; attempt is reserved before dispatch. Execute one repair iteration then stop for independentQA. No new authorization question, cycle reset, separate task or automatic next attempt.`,
'You are not alone in this repository. Own only causally connected game workspace files and this outputDirectory; preserve other work and all prior attempts. No shared factory, other games/levels, unrelated cleanup or commits. Source QA hash must match before edits. Read codex-game-repair and test-driven-development skills.',
`Use only this minimal issue packet, current reviewed contract, latest exact matrix, ${base}/failure-pressure-contract.json and ${base}/engineering-triage.json. Existing approved infrastructure research is ${run}/artifacts/open-source-research.json. Do not import full chat/old guesses; PENDING media remains excluded. A technical-design revision requires validating relevant open-source research first.`,
'Priority is actual Level1 relationships: restore interactive ladder/stack branches rather than collidable:false visual substitutes; support relationships and cut/separate/gravity must operate on the same visible objects. Fix established terminal band clipping and world-label correspondence. Keep existing Level1 gameplay scope and original content; do not copy competitor assets or numeric values.',
'The six existing unit failures are in unchanged game-core/catalog sources, not caused by renderer fixes. Determine root cause against the ACTIVE contract. Old hardcoded coordinate windows, fixture routes and density expectations are not automatically current requirements; if obsolete, replace them with stricter current-contract behavioral assertions and document the supersession. Do not skip/mark-todo/weaken tests, rewrite desired outcomes to match broken code, remove safe/bonus behavior, or distort game just to fit a bot cadence.',
'Any latest QA-only evidence gap is a diagnosis task, not automatic permission to invent mechanics. If source/runtime confirms a requirement violation (e.g. reward chronology), reproduce with a focused test and minimally fix; if only capture is missing, preserve gap for QA. Natural phone win unobserved does not by itself prove impossible completion. Preserve already passing opening branches and regression tests.',
'Before writing, create preflight.json with exact issue/object/state/renderer, smallest causal file set and RED checks. Test-first, lint/typecheck/full tests. After modifications and tests, pnpm build once only; do not run qa:* scripts which rebuild. Record every command exit code/log path and one build hash. Root then runs independent normal-input/perceptual retest of unchanged dist.',
'Return FixResultSchema-validated fix-result.json. Status only READY_FOR_INDEPENDENT_QA or BLOCKED, never productPASS. Include why formal route, omitted context, all changed files, actual root causes, tests and remaining gaps. No second build after one build in this attempt; further changes require next bounded attempt.'
],outputSchema:`${base}/schemas.ts#FixResultSchema`});writeFileSync(`${outputDirectory}/task.json`,JSON.stringify(task,null,2)+'\n',{flag:'wx'});state.attemptsStarted=n;state.currentAttempt=n;state.status='FIXING';state.attempts.push({attempt:n,taskPath:`${outputDirectory}/task.json`,status:'RESERVED',reservedAt:new Date().toISOString()});writeFileSync(`${base}/cycle-state.json`,JSON.stringify(state,null,2)+'\n');console.log(JSON.stringify({validated:true,attempt:n,issueIds:task.issues.map(i=>i.id),taskPath:`${outputDirectory}/task.json`}));
