import {finalChecksPass} from './final-checks.ts';
import{readFileSync,writeFileSync}from'node:fs';import{resolve}from'node:path';import{createHash}from'node:crypto';import{z}from'zod';import{ResultSchema,MatrixSchema}from'../qa-recovery-20260907/recovery-schemas.ts';import{QaReportSchema}from'../../../src/schemas/index.ts';import{PerceptualQaReportSchema}from'../../../src/schemas/product-experience.ts';import{FixResultSchema}from'./schemas.ts';
const base=resolve('runs/mobile-slice-adaptation-20260830/recovery-human-20260907'),n=Number(process.argv[2]);if(!Number.isInteger(n)||n<1||n>5)throw new Error('invalid attempt');const folder=`${base}/attempt-${n}`,qa=`${folder}/qa`,read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const fix=FixResultSchema.parse(read(`${folder}/fix-result.json`)),result=ResultSchema.parse(read(`${qa}/result.json`)),matrix=MatrixSchema.parse(read(`${qa}/reproduction-matrix.json`)),eng=QaReportSchema.parse(read(`${qa}/qa-report.json`)),percept=PerceptualQaReportSchema.parse(read(`${qa}/perceptual-qa-report.json`));
if(!fix.build||sha(fix.build.path)!==fix.build.sha256)throw new Error('current build differs');if(result.workspace!==fix.workspace||matrix.workspace!==fix.workspace)throw new Error('wrong workspace');for(const p of result.reportPaths)readFileSync(p);
const pass=result.status==='PASS'&&eng.passed&&percept.passed&&matrix.cells.every(c=>c.status==='PASS')&&finalChecksPass(fix.tests);
const Schema=z.object({schemaVersion:z.literal(1),cycleId:z.string(),attempt:z.number().int().min(1).max(5),status:z.enum(['PASS','BLOCKED']),buildSha256:z.string().length(64),matrixCounts:z.record(z.string(),z.number()),passingCheckIds:z.array(z.string()),remainingCheckIds:z.array(z.string()),evidence:z.array(z.object({path:z.string(),sha256:z.string().length(64)})),verifiedAt:z.string()}).strict();
const receipt=Schema.parse({schemaVersion:1,cycleId:fix.cycleId,attempt:n,status:pass?'PASS':'BLOCKED',buildSha256:fix.build.sha256,matrixCounts:matrix.cells.reduce((acc:Record<string,number>,c)=>({...acc,[c.status]:(acc[c.status]??0)+1}),{}),passingCheckIds:matrix.cells.filter(c=>c.status==='PASS').map(c=>c.id),remainingCheckIds:matrix.cells.filter(c=>c.status!=='PASS').map(c=>c.id),evidence:['result.json','reproduction-matrix.json','qa-report.json','perceptual-qa-report.json'].map(f=>({path:`${qa}/${f}`,sha256:sha(`${qa}/${f}`)})),verifiedAt:new Date().toISOString()});writeFileSync(`${folder}/qa-receipt.json`,JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});
const state=read(`${base}/cycle-state.json`);if(state.currentAttempt!==n)throw new Error('ledger mismatch');state.attemptsCompleted=n;state.attempts[n-1].status=receipt.status;state.attempts[n-1].qaReceiptPath=`${folder}/qa-receipt.json`;state.status=pass?'COMPLETE':n===5?'BLOCKED_MAX_ATTEMPTS':'READY_FOR_NEXT_FIX';writeFileSync(`${base}/cycle-state.json`,JSON.stringify(state,null,2)+'\n');console.log(JSON.stringify(receipt));
