import { readFileSync,writeFileSync } from 'node:fs';import { resolve } from 'node:path';import { createHash } from 'node:crypto';import {AuthorizationSchema,AttemptTaskSchema,DispatchSchema} from './schemas.ts';
const run=resolve('runs/mobile-slice-adaptation-20260830'),out=`${run}/recovery-human-20260907`,prior=`${run}/qa-recovery-20260907`,workspace=`${run}/workspace/prototype-a`;const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');const packet=JSON.parse(readFileSync(`${prior}/fixer-handoff.json`,'utf8'));const cycleId='human-review-20260907-l1-recovery';
const auth=AuthorizationSchema.parse({schemaVersion:1,cycleId,targetGame:packet.targetGame,workspace,authorizedAt:new Date().toISOString(),userReply:'是的',approvedProposal:'是否按这份清单启动新的人工复核修复周期，保留旧记录、最多5次？',reviewPackage:`${prior}/fixer-handoff.json`,reviewPackageSha256:hash(`${prior}/fixer-handoff.json`),previousLedger:`${prior}/repair-ledger.json`,previousLedgerSha256:hash(`${prior}/repair-ledger.json`),maximumAttempts:5,storedThreadId:packet.storedThreadId});
writeFileSync(`${out}/authorization.json`,JSON.stringify(auth,null,2)+'\n',{flag:'wx'});
const task=AttemptTaskSchema.parse({schemaVersion:1,role:'FixerAgent',route:'formal-fixer',cycleId,attempt:1,targetGame:packet.targetGame,workspace,authorizationPath:`${out}/authorization.json`,outputDirectory:`${out}/attempt-1`,issues:packet.issues.filter((i:any)=>['L1-OPENING-TABLE-BRANCH','L1-FIRST-TARGET-VISIBILITY'].includes(i.id)),matrixPath:`${prior}/independent-qa/reproduction-matrix.json`,contractPath:`${prior}/active-slice-contract.json`,expectedBuildSha256:hash(`${workspace}/dist/index.html`),instructions:[
'This is a newly explicitly human-authorized cycle after the reviewed recovery package. Preserve all older cycles/attempts; old executionAllowed:false in the review package describes the pre-authorization snapshot. New authorization.json governs this cycle. Root owns cycle-state.json. Attempt1 is reserved and counts even if interrupted or failed. Execute exactly one repair attempt and stop after producing result; do not start attempt2.',
'You are FixerAgent in the stored original thread01a07540-7ee1-7c01-899b-0ea12bde1f19. Other agents share the repository: preserve their changes. Own only causally connected files in the exact workspace plus outputDirectory. No shared factory edits, other games, other levels, unrelated cleanup, template replacements or commits. Do not use stale full thread history as current requirements; only this minimal artifact and bound evidence govern.',
'Read .agents/skills/codex-game-repair/SKILL.md and test-driven-development skill before production edits. Inspect exact opening-table-a/b support and rune-1 sigil intact branch; the matrix already exists. Identify owning branch and write preflight.json with issue IDs, minimal causally related allowed files and RED tests before editing. A visible cut-half is not evidence for an intact sigil.',
'Fix only two listed issues: opening support has visible grounded thickness with correct item support relation, and first whole target renders visibly before cutting on390x844 and1100x720. Keep original art direction; do not copy thirdparty assets/UI. Diagnose rather than guessing from console texture warnings. Inspect reference only if needed using prior/reference-frames/manifest.json; never PENDING screenshots.',
'Use test-first regression demonstrating the actual owning runtime renderer branch. Reuse architecture. Run lint,typecheck,tests with logs under outputDirectory. After source fixes and tests, run pnpm build exactly once and hash dist/index.html. Existing pnpm qa:* commands rebuild and must not be used. Root will run independent Playwright QA on your unchanged dist. You may inspect source/runtime via non-building preview if necessary, but cannot self-declare formal acceptance.',
'Return FixResultSchema validated JSON at outputDirectory/fix-result.json and final response only that structured artifact. Include route rationale, omitted context, root causes, changed files, RED/GREEN/lint/typecheck commands exit codes/logs, single build/hash, remaining natural/perceptual gaps. Do not claim fixed solely from tests or your own note. The result is READY_FOR_INDEPENDENT_QA or BLOCKED only.'
],outputSchema:`${out}/schemas.ts#FixResultSchema`});
writeFileSync(`${out}/attempt-1/task.json`,JSON.stringify(task,null,2)+'\n',{flag:'wx'});
writeFileSync(`${out}/cycle-state.json`,JSON.stringify({schemaVersion:1,cycleId,targetGame:packet.targetGame,workspace,maximumAttempts:5,attemptsStarted:1,attemptsCompleted:0,currentAttempt:1,status:'FIXING',authorizationPath:`${out}/authorization.json`,storedThreadId:packet.storedThreadId,historyPreserved:true,attempts:[{attempt:1,taskPath:`${out}/attempt-1/task.json`,status:'RESERVED',reservedAt:new Date().toISOString()}]},null,2)+'\n',{flag:'wx'});
const dispatch=DispatchSchema.parse({schemaVersion:1,role:'FixerAgent',taskPath:`${out}/attempt-1/task.json`,schemaPath:`${out}/schemas.ts#AttemptTaskSchema`,validation:'pnpm exec tsx runs/mobile-slice-adaptation-20260830/recovery-human-20260907/start.ts completed; AuthorizationSchema and AttemptTaskSchema parsed',instruction:'Resume stored thread as FixerAgent. Read and validate task artifact, execute exactly attempt1, return FixResultSchema artifact. No other attempts.'});
writeFileSync(`${out}/attempt-1/dispatch.json`,JSON.stringify(dispatch,null,2)+'\n');console.log(JSON.stringify(dispatch));
