import {readFileSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {z} from 'zod';import {TaskSchema} from './recovery-schemas.ts';
const root=resolve('runs/mobile-slice-adaptation-20260830');const out=`${root}/qa-recovery-20260907`;const sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const Schema=z.object({schemaVersion:z.literal(1),targetGame:z.string(),workspace:z.string(),source:z.object({path:z.string(),sha256:z.string().length(64),identityStatus:z.literal('VERIFIED_TARGET')}),method:z.literal('AVFoundation AVAssetImageGenerator appliesPreferredTrackTransform=true; extraction only, no edits'),frames:z.array(z.object({requestedSeconds:z.number(),actualSeconds:z.number(),path:z.string(),sha256:z.string().length(64)}))}).strict();
const source=`${root}/reference-evidence/incoming/_2026-09-06-135548-3781e4dcd3d2.mp4`;
const artifact=Schema.parse({schemaVersion:1,targetGame:'mobile-slice-adaptation-20260830',workspace:`${root}/workspace/prototype-a`,source:{path:source,sha256:sha(source),identityStatus:'VERIFIED_TARGET'},method:'AVFoundation AVAssetImageGenerator appliesPreferredTrackTransform=true; extraction only, no edits',frames:[[0,0],[6,5.791666666666667],[13,13.591666666666667],[21,21.258333333333333],[29,28.958333333333332],[34,34.858333333333334]].map(([requestedSeconds,actualSeconds])=>{const path=`${out}/reference-frames/reference-${requestedSeconds}.png`;return{requestedSeconds,actualSeconds,path,sha256:sha(path)}})});
writeFileSync(`${out}/reference-frames/manifest.json`,JSON.stringify(artifact,null,2)+'\n');
const previous=TaskSchema.parse(JSON.parse(readFileSync(`${out}/qa-task-update.json`,'utf8')));
const task=TaskSchema.parse({...previous,instructions:[...previous.instructions,`Reference video decoding resolved using native AVFoundation. Inspect extracted actual pixels now in ${out}/reference-frames/manifest.json (Zod validated, SHA-bound to VERIFIED recording, actual extraction times recorded). Use view_image for frames; these are genuine source frames, not synthetic. Update reference-observation report limitation accordingly. Parent has not changed generated source or dist.`]});
writeFileSync(`${out}/qa-task-reference-update.json`,JSON.stringify(task,null,2)+'\n');console.log(JSON.stringify({validated:true,frames:artifact.frames.length,taskPath:`${out}/qa-task-reference-update.json`}));
