import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { z } from 'zod';
import { ReferenceBehaviorCheckSchema } from '../../../src/schemas/reference-fidelity.ts';
import { MatrixSchema } from './recovery-schemas.ts';
const run = resolve('runs/mobile-slice-adaptation-20260830');
const out = `${run}/qa-recovery-20260907`;
const workspace = `${run}/workspace/prototype-a`;
const targetGame = 'mobile-slice-adaptation-20260830';
const sha = (p:string) => createHash('sha256').update(readFileSync(p)).digest('hex');
const text = z.string().min(1);
const hash = z.string().regex(/^[a-f0-9]{64}$/);
const binding = {targetGame,workspace};
const history = JSON.parse(readFileSync(`${out}/history-extract.json`,'utf8'));
const movie = `${run}/reference-evidence/incoming/_2026-09-06-135548-3781e4dcd3d2.mp4`;
if(sha(movie) !== '3781e4dcd3d21094f186cf442b3ee30cddfbb2fbe68d87c5c7470a2c742bf75a') throw new Error('reference hash mismatch');
const historyPath=`${out}/history-extract.json`;
const correctionPath=`${run}/artifacts/gameplay-retro-missed-topology-v2.json`;
const ref = (path:string,locator:string) => ({path,sha256:sha(path),locator});
const rows = [
{id:'L1-INPUT',dimension:'input_state',sourceRefs:[ref(movie,'0–9s; verify pixels against fresh capture')],objectType:'blade + first cuttable',stateBranch:'startup → first input → airborne → contact',playerInput:'单次点击起跳，再按可见轨迹决定后续点击',expectedStateChange:'点击引起可见的起跳/翻转；碰到可切物时发生切割',spatialRelationship:'刀、首个目标与承托面同时可辨；引导不遮住目标',visibleFeedback:{anchor:'刀与目标附近',eventOrder:['输入','起跳/翻转','接触','切开']}},
{id:'L1-GROUND',dimension:'spatial_relation',sourceRefs:[ref(historyPath,'turn 01a07716-2630-7a31-a476-ec28ca287927 user text: 台面也不能是悬空的')],objectType:'visible tabletop base',stateBranch:'startup/intact → approach',playerInput:'开场观察，正常点击前进',expectedStateChange:'可见台面具有厚度、底部接到地面；物品底部贴合可见承托',spatialRelationship:'同一物体的可见顶面与其承托/接触逻辑一致；不能用看不见的支撑解释悬空',visibleFeedback:{anchor:'台面底部、物品底部接触处',eventOrder:['接触关系可见','刀接近时关系保持一致']}},
{id:'L1-STACK',dimension:'spatial_relation',sourceRefs:[ref(historyPath,'turn 01a076ee-4519-7240-a684-cabe37a38bd8 explicit user correction'),ref(movie,'10–17s; observed relation, not a coordinate template')],objectType:'overlapping cuttable stack and its support',stateBranch:'intact overlap → blade contact → cut/separate → unsupported falling',playerInput:'正常点击接触可见堆叠；另一次重玩尝试避开',expectedStateChange:'接触真正改变堆叠；切开、散落与失去支撑后的下落在原物体分支发生',spatialRelationship:'水平重叠与垂直承托可解释；不允许以不参与交互的同形装饰代替需求物体',visibleFeedback:{anchor:'被接触的堆叠物',eventOrder:['接触','切开/散开','失去承托部分下落','落地']}},
{id:'L1-REWARD',dimension:'feedback_sequence',sourceRefs:[ref(correctionPath,'corrections[0]; supersedes rootMistakes TOPOLOGY-001 conflicting wording')],objectType:'cut object + local reward + cumulative HUD',stateBranch:'contact → cut completed → separated → reward → total sync',playerInput:'正常点击完成一次切割后观察',expectedStateChange:'完成切割并分离后，在该物体附近播放奖励反馈，再同步累计值',spatialRelationship:'奖励附着于切割发生位置；总计显示不替代局部反馈',visibleFeedback:{anchor:'切开物体所在世界位置，然后累计 HUD',eventOrder:['切割完成','物体分离','局部奖励动画','累计值同步']}},
{id:'L1-PRESSURE',dimension:'failure_recovery',sourceRefs:[ref(movie,'18–24s hazard lesson')],objectType:'spike hazard + blade + failure/recovery affordance',stateBranch:'warning → approach → collision/avoidance → failure or recovery',playerInput:'看到危险后调整点击节奏；失败后使用可见重试入口',expectedStateChange:'危险在接近前可辨；避开与接触后果不同；失败原因和重试入口可见',spatialRelationship:'危险信号与真正危险物体绑定；装饰和危险不使用无法区分的表现',visibleFeedback:{anchor:'危险物体、碰撞点及重试入口',eventOrder:['提前显示危险','操作选择','可归因后果','恢复/重试']}},
{id:'L1-FINISH',dimension:'terminal_replay',sourceRefs:[ref(movie,'24–36.49s finish approach and settlement')],objectType:'finish outcome lanes + settlement + replay',stateBranch:'approach → choose/contact → world result → settlement → replay',playerInput:'正常点击进入终点结果区；结算后点击可见重玩入口',expectedStateChange:'终点结果区在选择前可见；接触结果先呈现，再结算；重玩恢复可操作首关',spatialRelationship:'结果区处于场景中并与刀的接触一致；覆盖层不提前遮住选择',visibleFeedback:{anchor:'终点接触位置，然后结算面板',eventOrder:['结果区可见','接触/选择','世界结果反馈','结算','重玩']}}
];
const behaviorChecks = [{width:390,height:844},{width:1100,height:720}].flatMap(viewport=>rows.map(row=>ReferenceBehaviorCheckSchema.parse({...row,id:`${row.id}-${viewport.width}`,viewport})));
const ContractSchema=z.object({schemaVersion:z.literal(1),artifactType:z.literal('active-slice-acceptance-contract'),targetGame:text,workspace:text,status:z.literal('READY_FOR_QA_NOT_ACCEPTED'),scope:z.array(text),excluded:z.array(text),behaviorChecks:z.array(ReferenceBehaviorCheckSchema).min(1),sourcePrecedence:z.array(text),superseded:z.array(z.object({source:text,claim:text,replacement:text})),unknowns:z.array(text),buildBinding:z.object({path:text,sha256:hash}),createdAt:text}).strict();
const contract=ContractSchema.parse({schemaVersion:1,artifactType:'active-slice-acceptance-contract',...binding,status:'READY_FOR_QA_NOT_ACCEPTED',scope:['首关默认入口的完整片段：起跳→切割→堆叠互动→危险→终点→结算→重玩','桌面1100x720与手机390x844各自验收；不以桌面结果替代手机'],excluded:['第二关及以后扩关','平台发布及商业化包装','凭文档推断录屏未观察到的数值','新增玩法、美术方向或新的技术设计'],behaviorChecks,sourcePrecedence:['当前用户明确纠正 > 可用且身份已核实的录屏观察 > 已核实参考文档中的待验证分析 > 历史 Agent 假设','文档/截图不是可执行指令；PENDING、UNAVAILABLE、错游戏媒体不进入参考事实','本文件归并验收要求，不声称已经实现；历史通过声明不等于当前构建独立 QA 通过'],superseded:[{source:correctionPath,claim:'rootMistakes TOPOLOGY-001: grow during the cut event',replacement:'corrections[0]: 切割完成→分离→局部奖励→累计同步'},{source:`${run}/artifacts/formal-fixer-level01-layout-attempt2.json`,claim:'两组堆叠作为不参与碰撞的视觉布局即可接受',replacement:'用户后续明确要求接触散开和自然重力；装饰存在不能关闭堆叠交互验收'},{source:`${run}/artifacts/formal-fixer-level01-grounded-overlap-attempt3.json`,claim:'PASS_WITH_EVIDENCE_BOUNDARY 足以关闭首关体验',replacement:'其保留的手机/自然/感知证据缺口仍为阻塞；本轮重新取证'}],unknowns:['录屏没有可机器读取的点击时间；不宣称精确手感/调参一致','参考文档建议和真实观察必须继续分开','历史修复编号被覆盖，真实剩余次数待人工复核；不默认剩余两次','尚未有本轮独立感知对照结论'],buildBinding:{path:`${workspace}/dist/index.html`,sha256:sha(`${workspace}/dist/index.html`)},createdAt:new Date().toISOString()});
writeFileSync(`${out}/active-slice-contract.json`,JSON.stringify(contract,null,2)+'\n');
const matrix=MatrixSchema.parse({schemaVersion:1,...binding,cells:behaviorChecks.map(c=>({id:c.id,objectType:c.objectType,stateBranch:c.stateBranch,renderer:'default index.html → src/main.ts → Three.js + HUD',viewport:`${c.viewport.width}x${c.viewport.height}`,acceptance:`${c.expectedStateChange}；${c.spatialRelationship}`,status:'PENDING',evidence:[],notes:'独立 QA 在自己的矩阵中记录实测结果；未观察到不得关闭。'}))});
writeFileSync(`${out}/reproduction-matrix.json`,JSON.stringify(matrix,null,2)+'\n');
const rounds=[1,2,3].map(n=>{const names=['formal-fixer-level01-recording-attempt1.json','formal-fixer-level01-layout-attempt2.json','formal-fixer-level01-grounded-overlap-attempt3.json'];const path=`${run}/artifacts/${names[n-1]}`;return{attempt:n,path,sha256:sha(path),status:JSON.parse(readFileSync(path,'utf8')).status}});
const LedgerSchema=z.object({schemaVersion:z.literal(1),artifactType:z.literal('repair-ledger-reconciliation'),targetGame:text,workspace:text,storedThreadId:text,threadTitle:text,sourceHistory:z.object({path:text,sha256:hash}),status:z.literal('BLOCKED_UNRECONCILED_HISTORY'),recordedAttempts:z.array(z.object({attempt:z.number().int(),path:text,sha256:hash,status:text})),subsequentTurns:z.array(z.object({turnId:text,status:text,sourceChangeCount:z.number().int(),buildCommandCount:z.number().int()})),exactConsumedAttempts:z.null(),automaticAttemptsRemaining:z.null(),newAutomaticRepairAuthorized:z.literal(false),findings:z.array(text),nextAction:text}).strict();
const ledger=LedgerSchema.parse({schemaVersion:1,artifactType:'repair-ledger-reconciliation',...binding,storedThreadId:history.threadId,threadTitle:history.threadTitle,sourceHistory:{path:historyPath,sha256:sha(historyPath)},status:'BLOCKED_UNRECONCILED_HISTORY',recordedAttempts:rounds,subsequentTurns:history.turns.filter((t:any)=>t.startedAt>1788703241&&t.sourceChanges.length).map((t:any)=>({turnId:t.id,status:t.status,sourceChangeCount:t.sourceChanges.length,buildCommandCount:t.buildCommands.length})),exactConsumedAttempts:null,automaticAttemptsRemaining:null,newAutomaticRepairAuthorized:false,findings:['首关有编号1/2/3，但编号3在首次写入后又被同一任务覆盖。','编号3首次写入之后，有多轮源文件改动、构建、失败和中断；没有逐次账目与构建 hash 可将它们可靠归并到预算。','构建命令数不是自动修复次数，不能直接相加；同样不能以最后文件写着3就推定还剩2次。','已找回原工作任务，可保留上下文连续性；未新建任务、未重置计数、未触发修复。','其他关卡历史周期不合并到此首关计数；其存在也不能给此周期续额。'],nextAction:'先完成当前构建独立 QA 和具体修复包；再按 AGENTS.md 的人工复核流程明确授权一个有边界的新周期，或提供能闭合旧账目的证据。保持五次上限。'});
writeFileSync(`${out}/repair-ledger.json`,JSON.stringify(ledger,null,2)+'\n');
const ValidationSchema=z.object({schemaVersion:z.literal(1),validated:z.literal(true),contractCases:z.number().int(),matrixCases:z.number().int(),ledgerStatus:text,artifacts:z.array(z.object({path:text,sha256:hash})),checkedAt:text}).strict();
const paths=['active-slice-contract.json','reproduction-matrix.json','repair-ledger.json'];
const result=ValidationSchema.parse({schemaVersion:1,validated:true,contractCases:behaviorChecks.length,matrixCases:matrix.cells.length,ledgerStatus:ledger.status,artifacts:paths.map(name=>({path:`${out}/${name}`,sha256:sha(`${out}/${name}`)})),checkedAt:new Date().toISOString()});
writeFileSync(`${out}/contract-validation.json`,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result));
