import {readFileSync,writeFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {QaReportSchema} from '../../../../src/schemas/index.ts';
import {NaturalFlowEvidenceSchema} from '../../../../src/schemas/natural-flow.ts';
import {PerceptualQaReportSchema} from '../../../../src/schemas/product-experience.ts';
import {TaskSchema,MatrixSchema,ResultSchema} from '../recovery-schemas.ts';
const base=resolve('runs/mobile-slice-adaptation-20260830/qa-recovery-20260907'),out=`${base}/independent-qa`;
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const write=(name:string,value:unknown)=>{const p=`${out}/${name}`;writeFileSync(p,JSON.stringify(value,null,2)+'\n');return p;};
const task=TaskSchema.parse(read(`${base}/qa-task-recorder-correction.json`)),now=new Date().toISOString(),snapshot=read(`${out}/source-snapshot.json`);
const sourceDiagnosis=QaReportSchema.parse(read(`${base}/source-diagnosis.json`));
const hash=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const shots=(prefix:string)=>readdirSync(out).filter(x=>x.startsWith(`${prefix}-`)&&x.endsWith('.png')).map(x=>`${out}/${x}`);
const p=(name:string)=>`${out}/${name}`;
const correction=read(p('portrait-4-trace.json'));
const mobileWon=correction.observations.some((x:any)=>x.label==='terminal'&&x.state.status==='won');
const observed={input:'首个承托台面在开场可见，rune-1 初始 intact 未切状态已由只读状态确认，但台面上没有可辨的完整目标；首次输入后才出现带贴图碎片。分支为 sigil/intact，不可用后续 block 可见或 cut 碎片替代。',ground:'开场 opening-table-a 为薄浮板，底部未接地；white-landing/runway 的厚基座不能关闭这个不同 ID 分支。后续部分高台有柱体，但截图没有明确接触阴影。',stack:'可见上方绿色砖块与下方白台之间有明显空隙；没有取得同一个水平重叠堆叠 intact→接触→切开→失去承托下落→落地的完整像素链。自然轨迹中的单个目标/砖块切割不能关闭此分支。',reward:'截帧可见碎片、局部 +1 和 HUD 收益，但最低 550–800ms 采样和截图开销不足以确认切割完成→分离→局部奖励→累计同步的严格次序；未以事件计数推断感知通过。',pressure:'正常输入确实出现红色尖刺；portrait-2 发生 spike 失败并通过可见重玩按钮恢复。固定节奏没有证明玩家看到预警后改变节奏；失败截图中刀与致死尖刺空间关系不清晰，不能把内部 failReason 当作玩家可归因证据。',finish:'终点墙上方结果带被视口裁切，倍率只显示在右上极小图例，没有清楚绑定到墙的对应结果带。桌面已自然出现关卡完成 ×1 分数23并重玩；手机第三次仅观察到收益揭示 ×1·20（finishPhase=reward），随后过早点重玩，未取得完整赢结算。'};
const matrix=MatrixSchema.parse(read(`${base}/reproduction-matrix.json`));
for(const c of matrix.cells){const mobile=c.viewport==='390x844',prefix=mobile?'portrait-3':'desktop-1';const category=c.id.split('-')[1].toLowerCase() as keyof typeof observed;c.status=['input','ground','finish'].includes(category)?'FAIL':'BLOCKED';c.notes=observed[category];c.evidence=[p(`${prefix}-trace.json`)];if(category==='input'||category==='ground')c.evidence.push(p(`${prefix}-startup.png`),p(`${prefix}-tap-01.png`));if(category==='stack'||category==='pressure')c.evidence.push(p(mobile?'portrait-3-tap-10.png':'desktop-1-tap-07.png'));if(category==='reward')c.evidence.push(p(mobile?'portrait-2-tap-01.png':'desktop-1-tap-04.png'));if(category==='finish')c.evidence.push(p(`${prefix}-terminal.png`),p(mobile?'portrait-3-tap-25.png':'desktop-1-tap-16.png'));}
for(const c of matrix.cells.filter(x=>x.id.includes('FINISH'))){c.notes=c.notes.replace('手机第三次仅观察到收益揭示 ×1·20（finishPhase=reward），随后过早点重玩，未取得完整赢结算。',mobileWon?'手机第4次使用修正的采集器，已等待完整关卡完成后再点重玩；前次提前重玩的采集缺口已解决。':'手机第4次采用已修正采集器，第4次在x≈1484自然撞尖刺失败，已确认真实失败面板后才重玩；未到终点，30秒等待结算条件未触发。手机完整赢结算仍缺证，不等同于游戏无法结算。');c.evidence.push(p('portrait-4-trace.json'),p('portrait-4-end.png'));}
const pressure390=matrix.cells.find(c=>c.id==='L1-PRESSURE-390')!;
pressure390.notes+=' 追加portrait-4-tap-13截图已明确显示刀尖接近红尖刺，随后真实危险失败面板并重玩，改善了接近→后果链证据。固定节奏仍未证明基于提前预警的有意回避决策。';
pressure390.evidence.push(p('portrait-4-tap-13.png'),p('portrait-4-terminal.png'),p('portrait-4-replay.png'),p('portrait-4-trace.json'));
const matrixPath=write('reproduction-matrix.json',MatrixSchema.parse(matrix));
const TriageSchema=z.object({schemaVersion:z.literal(1),targetGame:z.string(),workspace:z.string(),route:z.literal('formal-fixer'),items:z.array(z.object({id:z.string(),classification:z.string(),scope:z.array(z.string()),reproduction:z.string(),evidence:z.array(z.string()),acceptance:z.string(),rootCauseStatus:z.literal('NOT_ACCEPTED')})),contextOmitted:z.array(z.string())});
write('triage.json',TriageSchema.parse({schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,route:'formal-fixer',items:matrix.cells.filter(x=>x.status==='FAIL').map(x=>({id:x.id,classification:'player-visible-acceptance-failure',scope:['Level 1',x.objectType,x.viewport],reproduction:`默认 index.html，新浏览器上下文；固定间隔普通输入。${x.notes}`,evidence:x.evidence,acceptance:x.acceptance,rootCauseStatus:'NOT_ACCEPTED'})),contextOmitted:['其他关卡和游戏','PENDING截图的像素','平台包装','历史通过结论','未执行修复和重建；未推定剩余修复次数']}));
const paths:string[]=[matrixPath];
write('source-diagnosis-receipt.json',{schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,path:`${base}/source-diagnosis.json`,zodValidated:true,engineeringPassed:sourceDiagnosis.passed,interpretation:'父任务的精确源分支事实作为独立工程证据保存；不用于关闭自然操作或感知矩阵。未接受贴图警告作为首个intact缺失的根因。'});
for(const prefix of ['portrait-1','portrait-2','portrait-3','portrait-4','desktop-1']){
 const t=read(p(`${prefix}-trace.json`)),win=prefix==='desktop-1'||(prefix==='portrait-4'&&mobileWon),failed=prefix==='portrait-2'||(prefix==='portrait-4'&&t.observations.some((x:any)=>x.label==='terminal'&&x.state.status==='failed')),completion=win?'settlement':failed?'terminal':'none';
 const blockers=prefix==='portrait-1'?['QA 首次探测错误地把始终可见的重玩按钮当终点；terminal 标签处实际 airborne。保留原始记录且排除终点证明。']:prefix==='portrait-3'?['手机在 finishPhase=reward 时提前重玩；没有完整赢结算截图。']:[];
 const report=NaturalFlowEvidenceSchema.parse({schemaVersion:1,startedFromReset:true,actions:[`新 Chromium 上下文，未注入任何存储；${t.inputPolicy}`,'按预先声明固定等待间隔点击；只读状态用于事后断言，不用于决定点击',`原始操作及截图：${p(`${prefix}-playwright-trace.zip`)}`],transitions:[{name:`${prefix}:startup-to-core`,changed:true,evidence:p(`${prefix}-trace.json`)},{name:`${prefix}:terminal`,changed:win||failed,evidence:p(`${prefix}-terminal.png`)},{name:`${prefix}:visible-replay-to-ready`,changed:true,evidence:p(`${prefix}-replay.png`)}],completion,replayObserved:true,forbiddenOperations:[],screenshots:shots(prefix),passed:blockers.length===0,blockers,runner:'independent-QAAgent-fixed-cadence',buildHash:snapshot.buildHash,runtime:'Chromium / existing default dist/index.html; no rebuild',device:{...t.device,label:prefix},observedAt:now});
 paths.push(write(`${prefix}-natural-flow.json`,report));
}
const blockers=['L1-INPUT-390/1100：首个 intact 目标不可辨；切开碎片可见不能替代。','L1-GROUND-390/1100：开场浮薄台面分支未落地；厚 runway 通过不能关闭该分支。','L1-STACK-390/1100：精确重叠堆叠→受击→自然落地链未观察。','L1-REWARD-390/1100：局部奖励与累计同步严格时序证据不足。','L1-PRESSURE-390/1100：提前预警和空间可归因的自然决策证据不足。','L1-FINISH-390/1100：结果带裁切且倍率未清晰附着；手机完整赢结算未观察。'];
paths.push(write('qa-natural-journey-report.json',NaturalFlowEvidenceSchema.parse({schemaVersion:1,startedFromReset:true,actions:['桌面1次与手机原3次加1次采集器纠错 fresh-context 普通输入；未使用debug URL、setter、fixture、存储注入、事件分发或状态驱动自动点击','portrait-1的terminal标签无效；portrait-3的terminal仅为收益揭示。分别保留，未合成胜利','固定节奏并非真实人类反应测试；实际间隔包含截图与观察开销'],transitions:matrix.cells.map(c=>({name:c.id,changed:false,evidence:matrixPath})),completion:'settlement',replayObserved:true,forbiddenOperations:[],screenshots:[...shots('portrait-2'),...shots('portrait-3'),...shots('portrait-4'),...shots('desktop-1')],passed:false,blockers,runner:'independent-QAAgent-combined-gate',buildHash:snapshot.buildHash,runtime:'desktop settlement observed; does not waive mobile gaps',observedAt:now})));
paths.push(write('perceptual-qa-report.json',PerceptualQaReportSchema.parse({schemaVersion:1,artifactType:'perceptual-qa-report',game:task.targetGame,passed:false,checkedAt:now,features:matrix.cells.map(c=>({featureId:c.id,playerVisible:c.status==='PASS',naturalTriggerVerified:c.status==='PASS',screenshotEvidence:c.evidence.filter(x=>x.endsWith('.png')),evidence:[...c.evidence,matrixPath],notes:[`${c.status}: ${c.notes}`]}))})));
const unchanged=snapshot.files.every((x:{path:string;sha256:string})=>hash(x.path)===x.sha256);
const raw=['portrait-1','portrait-2','portrait-3','portrait-4','desktop-1'].flatMap(x=>read(p(`${x}-console.json`)).map((m:unknown)=>({run:x,message:m})));
const consolePath=write('console.json',raw);
const desktop=read(p('desktop-1-trace.json')),phone=read(p('portrait-2-trace.json'));
paths.push(write('qa-report.json',QaReportSchema.parse({schemaVersion:1,passed:false,checks:[{name:'unchanged current source/dist identity',passed:unchanged,evidence:p('source-snapshot.json')},{name:'fresh default level1 input changes state and cuts',passed:desktop.observations[1].state.cuts>0,evidence:p('desktop-1-trace.json')},{name:'desktop natural won then replay ready',passed:desktop.observations.some((x:any)=>x.label==='terminal'&&x.state.status==='won'),evidence:p('desktop-1-trace.json')},{name:'portrait natural spike failure then replay',passed:phone.observations.some((x:any)=>x.state.status==='failed'&&x.state.failReason==='spike'),evidence:p('portrait-2-trace.json')},{name:'no page exceptions/console errors',passed:raw.every((x:any)=>!['pageerror','error'].includes(x.message.kind)),evidence:consolePath},{name:'exact overlapping intact stack deterministic collision coverage',passed:false,evidence:matrixPath},{name:'complete mobile winning settlement observed (recorder corrected; natural run failed before finish)',passed:mobileWon,evidence:p('portrait-4-trace.json')}],issues:[{id:'QA-EXACT-BRANCH-COVERAGE',severity:'error',message:'精确分支存在未覆盖项；工程状态变化不构成感知通过。',evidence:matrixPath},{id:'QA-TEXTURE-WARNINGS',severity:'warning',message:'各上下文捕获 Texture marked for update but no image data found 警告，未接受其为缺失 intact 外观的根因。',evidence:consolePath}],screenshots:shots('desktop-1'),consoleLog:consolePath,testedAt:now})));
const ref=read(p('reference-observation.json'));
const referenceFrames=read(`${base}/reference-frames/manifest.json`);
if(referenceFrames.targetGame!==task.targetGame||referenceFrames.workspace!==task.workspace||referenceFrames.source.sha256!==ref.sha256||referenceFrames.frames.some((f:any)=>hash(f.path)!==f.sha256))throw new Error('Reference identity mismatch');
write('reference-observation.json',{...ref,errorResolved:true,resolution:'父任务使用原生AVFoundation抽取实际帧，本QA已逐张view_image检查并重算SHA-256。',frameManifest:`${base}/reference-frames/manifest.json`,inspectedFrames:referenceFrames.frames,thumbnail:p('_2026-09-06-135548-3781e4dcd3d2.mp4.png'),thumbnailInspected:true,thumbnailTimestamp:'Quick Look selected; unknown exact time',observations:['0s：完整首批目标在白台上方可见且接触台面；白台具有落地侧壁及接触阴影。当前首个 intact 目标缺失、开场承托薄板浮空。','5.79s：切片分离且奖励文字位于切割处附近。当前截帧有局部奖励，但不足以确认严格时序。','13.59s：横档依靠可见立柱，各组高低关系可读；当前绿色砖块与下方白台分离，精确可交互重叠堆叠仍缺证。','21.26s：高对比尖刺垫在接近路径上突出可见，周围有足够空白分辨危险轮廓。当前失败截图中碰撞原因的空间关系不清晰。','28.96s：墙上每条可见结果带有贴近的倍率，选择位置可归因。当前墙上无清晰倍率，仅右上小图例。','34.86s：世界终点背景仍保留，结算面板给出分数、奖励、结果与最佳纪录。当前桌面展示完成和分数，未见最佳纪录；手机只有收益揭示中间态。'],limitations:['六张实际帧提供空间/呈现比较，不能恢复逐次点击时间或证明精确奖励同步顺序。未完整连续播放0–36.49s，不复制任何表达、美术或数值。'],excluded:'manifest中的PENDING截图从未查看或用作证据'});
paths.push(p('source-snapshot.json'),p('reference-observation.json'),p('triage.json'));
write('methodology.json',{targetGame:task.targetGame,workspace:task.workspace,role:'QAAgent',skill:'.agents/skills/game-playtest/SKILL.md',sourceModified:false,rebuilds:0,route:'independent-qa-only',sourceUnchanged:unchanged,defaultEntrypoints:[`${task.workspace}/index.html`,`${task.workspace}/src/main.ts`,`${task.workspace}/src/three-presentation.ts`,`${task.workspace}/src/three-world-renderer.ts`,`${task.workspace}/src/three-cut-visuals.ts`],attempts:{portrait:4,desktop:1,portraitCorrection:1},knownRunnerLimitations:['portrait-1 premature replay during airborne; never counted terminal','portrait-3 premature replay during reward reveal preserved; recorder detection corrected in portrait-4, which naturally failed on spike before reaching finish','Screenshots may add wall time to fixed minimum cadence; no exact cadence or human adaptability claim','Fresh context startup, normal input only; getState observation only; no isolated deterministic state injection track because task forbids it'],pixelInspection:['portrait-1-startup','portrait-2-tap-01','portrait-2-tap-07','portrait-2-terminal','portrait-3-tap-10','portrait-3-tap-25','portrait-3-terminal','portrait-3-replay','portrait-4-tap-13','portrait-4-terminal','portrait-4-replay','desktop-1-startup','desktop-1-tap-01','desktop-1-tap-04','desktop-1-tap-07','desktop-1-tap-10','desktop-1-tap-16','desktop-1-terminal','verified recording Quick Look thumbnail'],remainingEvidenceGaps:blockers,cleanup:'all Chromium contexts and localhost servers closed in finally'});
function files(dir:string):string[]{return readdirSync(dir).sort().flatMap(n=>statSync(`${dir}/${n}`).isDirectory()?files(`${dir}/${n}`):[`${dir}/${n}`]);}
write('evidence-sha256.json',{schemaVersion:1,targetGame:task.targetGame,workspace:task.workspace,buildHash:snapshot.buildHash,files:files(out).filter(x=>!x.endsWith('/evidence-sha256.json')&&!x.endsWith('/result.json')).map(path=>({path,sha256:hash(path)}))});
paths.push(p('evidence-sha256.json'),p('methodology.json'));
const result=ResultSchema.parse({schemaVersion:1,role:'QAAgent',targetGame:task.targetGame,workspace:task.workspace,status:'BLOCKED',reportPaths:paths,blockers,sourceModified:false,summary:'独立QA已完成当前首关默认构建取证与Zod校验：桌面自然完成×1并重玩，手机自然尖刺失败可重玩；额外1次已修正提前重玩的采集逻辑，手机第4次在终点前自然尖刺失败，随后才点击重玩。手机赢结算仍缺证，不据此断言游戏无法结算。首个完整目标、浮空台面、精确堆叠受击落地、奖励时序、危险归因及终点可读性仍不满足或缺证。只修改独立QA输出目录，未修复、未重建。'});
write('result.json',result);console.log(JSON.stringify(result));
